### create entity
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "moam.statemanager",
  "actionName": "CreateEntityAction",
  "params": {
    "definition": "{\n  \"apiVersion\": \"kubernetes.crossplane.io/v1alpha2\",\n  \"kind\": \"Object\",\n  \"metadata\": {\n    \"name\": \"themis-test\"\n  },\n  \"spec\": {\n    \"forProvider\": {\n      \"manifest\": {\n        \"apiVersion\": \"v1\",\n        \"kind\": \"Namespace\",\n        \"metadata\": {\n          \"name\": \"themis-test\"\n        }\n      }\n    },\n    \"providerConfigRef\": {\n      \"name\": \"provider-config-kubernetes\"\n    }\n  }\n}"
  }
}

### update entity
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "moam.statemanager",
  "actionName": "UpdateEntityAction",
  "params": {
    "query": "select * from entity where api_version = 'kubernetes.crossplane.io/v1alpha2' and kind = 'Object' and name = 'themis-test'",
    "lambdas": "{\".spec.forProvider.manifest.metadata.name\": \". + \\\"-updated\\\"\"}"
  }
}

### delete entity
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "moam.statemanager",
  "actionName": "DeleteEntityAction",
  "params": {
    "query": "select * from entity where api_version = 'kubernetes.crossplane.io/v1alpha2' and kind = 'Object' and name = 'themis-test'"
  }
}

### read entity
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "moam.statemanager",
  "actionName": "ReadEntityAction",
  "params": {
    "query": "select * from entity where definition->'$.metadata.name' = 'themis-test'"
  }
}

### trigger-mm test create
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "moam.statemanager",
  "actionName": "CreateEntityAction",
  "params": {
    "definition": "{\n  \"apiVersion\": \"kubernetes.crossplane.io/v1alpha2\",\n  \"kind\": \"Object\",\n  \"metadata\": {\n    \"name\": \"trigger-mm-test\"\n  },\n  \"spec\": {\n    \"forProvider\": {\n      \"manifest\": {\n        \"apiVersion\": \"v1\",\n        \"kind\": \"Namespace\",\n        \"metadata\": {\n          \"name\": \"trigger-mm-test\"\n        }\n      }\n    },\n    \"providerConfigRef\": {\n      \"name\": \"provider-config-kubernetes\"\n    }\n  }\n}",
    "triggerMirrorManager": "false"
  }
}

### trigger-mm test delete
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "moam.statemanager",
  "actionName": "DeleteEntityAction",
  "params": {
    "query": "select * from entity where name = 'trigger-mm-test'",
    "triggerMirrorManager": "false"
  }
}
