package org.k8loud.executor.exception.code;

public enum CNAppExceptionCode {
    SOCK_SHOP_REGISTER_USER_FAILED,
    SOCK_SHOP_DELETE_USER_FAILED,
    SOCK_SHOP_CREATE_ADDRESS_FAILED,
    SOCK_SHOP_DELETE_ADDRESS_FAILED,
    SOCK_SHOP_NOTIFY_CUSTOMERS_FAILED,

    MESSAGE_CREATE_FAILED,
    MESSAGE_UPDATE_FAILED,
    MESSAGE_GET_FAILED,
    MESSAGE_DELETE_FAILED,
    MESSAGE_NOT_EXISTS
}
